### PR TITLE
added input for merge tags

### PR DESCRIPTION
**Pull request by jondcallahan**
Was trying to use template_content for merge tags, but it only supported one. I added the merge_vars field to allow users to input multiple unique merge tags and content.

### CODE REVIEW

**Comment by sgress454** [comment]
This is almost there but needs a couple of tweaks:
1. Remove `typeclass: "array"` from the `mergeVars` input definition
2. Change the example for `mergeVars` to only have one item in the array (i.e. one object with "name" and "content" keys instead of two)

Then you can test that the machine works with your changes.  Normally you can do that by installing the machinepack runner (`npm install machinepack`) and running `mp exec` on the command line, but in this case it might be easier to write a little script since the `mergeVars` input is JSON.  Something like:

```
require('./').sendTemplateEmail({
   apiKey: "theapikey",
   toEmail: "john@doe.com",
   templateName: "Welcome",
   mergeVars: [{'name': 'foo', 'content': 'bar'}]
}).exec(console.log);
```

then save it as `test.js` and run on the command line with `node test.js`

**Comment by jondcallahan** [comment]
Thanks for the feedback. I've changed the file, successfully tested, and recommitted with the changes.

**Comment by alexlenail** [comment]
You should consider adding merge vars to sendPlaintextEmail as well while you're at it, and perhaps even global merge vars. Either way, well done on the PR.

**Comment by sgress454** [comment]
Sorry about the delay on this, taking a look now.

**Pull request merged**
